config/routes.rb
Rails.application.routes.draw do
  get 'notes/index'
  get 'notes/edit'
  get 'notes/show'
  get 'notes/new'
  root 'static_pages#home'
  
  get '/about', to: 'static_pages#about'
  
  get '/home', to: 'static_page#home'

  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
    has_many :notes, dependent: :destroy

    def full_name
        "#{self.first_name} #{self.last_name}"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :get_person
  #copy & adjust language from person_controller as applicable
  #THEN update Notes>Html pages (can use content from Pages>html)
  def index
    @notes = Note.all
  end

  def edit
    @note = Note.find(params[:id])
  end
  
  def update
    @note = Note.find(params[:id])
    if @person.update(person_params)
      redirect_to person_path(@person.id)
    else
      render: edit
    end
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = @person.notes.build
  end

  def create
    @note = Note.new(note_params)
    @note.person_id = params[:person_id]
    if @note.save 
      redirect_to person_path(@note.person_id)
    else
      render :new
  end

  def destroy
    Note.find(params[:id])
    .destroy
    redirect_to people_path
  end

  def get_person
    @oerson = Person.find(params[:id])
  end

  private
  def note_params
    params.require(:body)
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to person_path(@person.id)
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to person_path(@person.id)
    else
      render :edit
    end
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end

  private
  def person_params
    params.require(:person).permit(:first_name, :last_name, :age, :hair_color, :eye_color, :gender, :alive)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'People', people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>People</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h1>Edit Note:</h1>

<%= form_for @note do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body %>

    <%= f.submit %>
<% end %>

app/views/notes/index.html.erb
<h1>Notes#index</h1>
<p>Find me in app/views/notes/index.html.erb</p>

app/views/notes/new.html.erb
<h1>New Note:</h1>

<%= form_for @note do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body %>

    <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<h1>Notes#show</h1>
<p>Find me in app/views/notes/show.html.erb</p>

app/views/people/edit.html.erb
<h1>Edit Person:</h1>

<%= form_for @person do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>

    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>

    <%= f.label :gender %>
    <%= f.text_field :gender %>

    <%= f.label :alive %>
    <%= f.text_field :alive %>

    <%= f.label :notes %>
    <%= f.text_field :notes %>

    <%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h1>People</h1>
<button><%= link_to 'New Person', new_person_path %></button>


<% @people.each do |p| %>
    <h4><%= link_to p.full_name, person_path(p.id) %><h4>
<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>
<%= form_for @person do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>

    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>

    <%= f.label :gender %>
    <%= f.text_field :gender %>

    <%= f.label :alive %>
    <%= f.text_field :alive %>

    <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1><%= @person.full_name %></h1>
<h4>Age: <%= @person.age %><h4>
<h4>Hair color: <%= @person.hair_color %></h4>
<h4>Eye color: <%= @person.eye_color %></h4>
<h4>Gender: <%= @person.gender %></h4>
<h4>Alive: <%= @person.alive %></h4>
<h4>Notes: <%= @person.notes.body %></h4>

<ul>
    <li><%= link_to 'Edit Person', edit_person_path(@person) %></li>
    <li><%= link_to 'Delete Person', @person, method: :delete %></li>
    <li><%= link_to 'Back', people_path %></li>
    </ul>

app/views/static_pages/about.html.erb
<h1>About 'People'</h1>
<p>The People app is here to help you keep track of the humans in your life.</p>

app/views/static_pages/home.html.erb
<h1>Home</h1>

<p><%= link_to "My People", people_path %></p>


<div><button><%= link_to 'New Person', new_person_path %></button></div>